const Actions = {
    SET_DATA_IN_STORE: 'SET_DATA_IN_STORE',
    GET_DATA: 'GET_DATA',
    GET_VIEW: 'GET_VIEW',
    INPUT_VIEW_RECEIVED: 'INPUT_VIEW_RECEIVED',
    GET_VIEW_TEXTAREA: 'GET_VIEW_TEXTAREA',
    TEXTAREA_VIEW_RECEIVED: 'TEXTAREA_VIEW_RECEIVED',
    GET_VIEW_SELECT_OPTION: 'GET_VIEW_SELECT_OPTION',
    SELECT_OPTION_VIEW_RECEIVED: 'SELECT_OPTION_VIEW_RECEIVED',
    KEEP_DATA_IN_FORM: 'KEEP_DATA_IN_FORM',
    SELECT_ELEMENT: 'SELECT_ELEMENT',
    GET_LIST_DATA: 'GET_LIST_DATA',
    SET_LIST_ITEMS: 'SET_LIST_ITEMS',
    GET_ELEMENT_DATA: 'GET_ELEMENT_DATA'
};

export default Actions;